[package]
name = "website"
version = "0.1.0"
authors = ["samuel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.9.2"
plotters = "0.2.8"